name: kbmag
version: 1.5.11
date: 2023-01-03
description: |
    Knuth-Bendix on Monoids and Automatic Groups

authors:
    - name: Derek Holt
      url: https://homepages.warwick.ac.uk/staff/D.F.Holt/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.7"

www: https://gap-packages.github.io/kbmag
readme: README.md
packageinfo: https://gap-packages.github.io/kbmag/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/kbmag/releases/download/v1.5.11/kbmag-1.5.11.tar.gz

abstract: |
    The <span class="pkgname">kbmag</span> package is a       <span class="pkgname">GAP</span> interface to some `C' programs   for running the Knuth-Bendix completion program on finite semigroup,   monoid or group presentations, and for attempting to compute automatic   structures of finitely presented groups

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
