name: kbmag
version: "1.6.0"
license: "GPL-2.0-or-later"
date: 2026-08-15
description: |
    Knuth-Bendix on Monoids and Automatic Groups

authors:
    - name: Derek Holt
      url: https://homepages.warwick.ac.uk/staff/D.F.Holt/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.7"

www: https://gap-packages.github.io/kbmag
readme: README.md
packageinfo: https://gap-packages.github.io/kbmag/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/kbmag/releases/download/v1.6.0/kbmag-1.6.0.tar.gz

abstract: |
    The <span class="pkgname">kbmag</span> package is a       <span class="pkgname">GAP</span> interface to some `C' programs   for running the Knuth-Bendix completion program on finite semigroup,   monoid or group presentations, and for attempting to compute automatic   structures of finitely presented groups

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Knuth-Bendix, Automatic Groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Hol26</span>]   <b class='BibAuthor'>Holt, D.</b>,
     <i class='BibTitle'>kbmag, Knuth-Bendix on Monoids and Automatic Groups,
             Version 1.6.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/kbmag">https://gap-packages.github.io/kbmag</a></span>.
    </p>
    

bibtex: |
    @misc{ kbmag,
      author =           {Holt, D.},
      title =            {{kbmag},  {Knuth\texttt{\symbol{45}}Bendix  on Monoids
                          and Automatic Groups}, {V}ersion 1.6.0},
      month =            {Aug},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/kbmag}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{kbmag}}},
      keywords =         {Knuth\texttt{\symbol{45}}Bendix; Automatic Groups},
      printedkey =       {Hol26}
    }

