#!/bin/sh

echo "TeXing documentation"
# TeX the manual
tex manual
# ... and build its bibliography (uncomment if there is a `manual.bib')
bibtex manual
# TeX the manual again to incorporate the ToC ... and build the index
tex manual
tex manual
../../../doc/manualindex manual
# Finally TeX the manual again to get cross-references right
tex manual
# Create the PostScript version (uncomment next line, if needed)
#dvips -D300 manual -o
# Create PDF version
pdftex manual; pdftex manual 

# The HTML version of the manual
mkdir -p ../htm
echo "Creating HTML documentation"
../../../etc/convert.pl -t -c -n kbmag . ../htm

#############################################################################
##
#E
